create schema if not exists petclinic;

CREATE TABLE IF NOT EXISTS petclinic.vets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT
);
CREATE INDEX ON petclinic.vets (last_name);

CREATE TABLE IF NOT EXISTS petclinic.specialties (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX ON petclinic.specialties (name);

CREATE TABLE IF NOT EXISTS petclinic.vet_specialties (
  vet_id       INT NOT NULL REFERENCES petclinic.vets (id),
  specialty_id INT NOT NULL REFERENCES petclinic.specialties (id),
  UNIQUE (vet_id, specialty_id)
);

CREATE TABLE IF NOT EXISTS petclinic.types (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX ON petclinic.types (name);

CREATE TABLE IF NOT EXISTS petclinic.owners (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT,
  address    TEXT,
  city       TEXT,
  telephone  TEXT
);
CREATE INDEX ON petclinic.owners (last_name);

CREATE TABLE IF NOT EXISTS petclinic.pets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT,
  birth_date DATE,
  type_id    INT NOT NULL REFERENCES petclinic.types (id),
  owner_id   INT REFERENCES petclinic.owners (id)
);
CREATE INDEX ON petclinic.pets (name);
CREATE INDEX ON petclinic.pets (owner_id);

CREATE TABLE IF NOT EXISTS petclinic.visits (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id      INT REFERENCES petclinic.pets (id),
  visit_date  DATE,
  description TEXT
);
CREATE INDEX ON petclinic.visits (pet_id);
