package org.eipgrid.jql.sample.jpa.starwars.model;

import lombok.Getter;
import lombok.Setter;
import java.util.List;
import javax.persistence.*;

/** This is generated by JQL-JDBC */

@Entity
@Table(name = "episode", schema = "starwars_jpa",
        uniqueConstraints = {
                @UniqueConstraint(name ="episode_pkey", columnNames = {"title"})
        }
)
public class Episode implements java.io.Serializable {
    @Getter @Setter
    @Id
    @Column(name = "title", nullable = false)
    String title;

    @Getter @Setter
    @Column(name = "published")
    java.sql.Timestamp published;

    @Getter @Setter
    @OneToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "character_episode_link", schema = "starwars_jpa",
            joinColumns = @JoinColumn(name="episode_id"), inverseJoinColumns = @JoinColumn(name="character_id"))
    List<Character> character_;

}
